defmodule ElectricbrainWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :electricbrain

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_electricbrain_key",
    signing_salt: "QTzjmA7F",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :electricbrain,
    gzip: not code_reloading?,
    only: ElectricbrainWeb.static_paths(),
    # Prod resolves ~p"/manifest.webmanifest" through cache_static_manifest
    # to `/manifest-<hash>.webmanifest`, whose first path segment isn't in
    # `only:` (exact match). Match those root-level digested filenames by
    # prefix here so the browser can fetch them.
    only_matching: ~w(favicon manifest robots service-worker),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :electricbrain
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # JSON limit raised from the 8MB default: Health Auto Export relay
  # posts to /api/ingest/measurements can be tens of MB when the phone
  # backfills raw samples. Multipart/urlencoded keep their defaults.
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, {:json, length: 50_000_000}],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # CORS for the /api/g2/* surface used by the Even Hub plugin —
  # WebView origins are opaque and the API is bearer-protected, so
  # `*` is the right scope. Placed before the router so that OPTIONS
  # preflights are answered (the router rejects unknown methods on a
  # path before pipelines run).
  plug CORSPlug,
    origin: "*",
    methods: ["GET", "POST", "DELETE", "OPTIONS"],
    headers: ["authorization", "content-type", "accept"],
    max_age: 86_400

  plug ElectricbrainWeb.Router
end
