import Config
config :ash, policies: [show_policy_breakdowns?: true]

# Configure your database
config :electricbrain, Electricbrain.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "electricbrain_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :electricbrain, ElectricbrainWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "OTYbhQq+Mc8K/i0stimEaj2xMBJ5QsITNczS48wdjD309TjmhjWsMdFLvvxqTxwO",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:electricbrain, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:electricbrain, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :electricbrain, ElectricbrainWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/electricbrain_web/router\.ex$"E,
      ~r"lib/electricbrain_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :electricbrain, dev_routes: true, token_signing_secret: "VCsAolsdHD2erz0lamIA9KVyMqWtj92T"

# Google Calendar OAuth (per-user). For local dev, set GOOGLE_CLIENT_ID and
# GOOGLE_CLIENT_SECRET in your env; without them the Connect button will
# render but the OAuth start endpoint will raise — that's acceptable for dev.
if google_client_id = System.get_env("GOOGLE_CLIENT_ID") do
  config :electricbrain,
    google_client_id: google_client_id,
    google_client_secret: System.get_env("GOOGLE_CLIENT_SECRET")
end

# Web push (VAPID) — local dev keypair. Regenerate with
# `mix generate.vapid.keys` for prod and set VAPID_PUBLIC_KEY +
# VAPID_PRIVATE_KEY env vars. The dev pair here only works against this
# checkout's browser subscriptions — they are tied to the public key.
config :web_push_elixir,
  vapid_public_key:
    "BMxPa5w1smIyaeqaCy3nqcZ3C0j0W_SoAGcASJXnoBzAUVfys570QVvCIdMns6L1hDx7A5y8l2ZOanhCc5xU4MM",
  vapid_private_key: "Y0aQxcmHGLyvXFpYtB_LSMbyjGpvSh8kIq3s_dGI_Xo",
  vapid_subject: "mailto:ben.kolera@gmail.com"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
