defmodule Electricbrain.Repo.Migrations.AddIngestTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:nutrition_profiles) do
      add :body_fat_metric_id,
          references(:metrics,
            column: :id,
            name: "nutrition_profiles_body_fat_metric_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:device_pairings) do
      add :kind, :text, null: false, default: "g2"
    end
  end

  def down do
    alter table(:device_pairings) do
      remove :kind
    end

    drop constraint(:nutrition_profiles, "nutrition_profiles_body_fat_metric_id_fkey")

    alter table(:nutrition_profiles) do
      remove :body_fat_metric_id
    end
  end
end
