defmodule Electricbrain.Repo.Migrations.AddPlannerEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:plan_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :week_start, :date, null: false
      add :planned_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "plan_entries_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :todo_id,
          references(:todos,
            column: :id,
            name: "plan_entries_todo_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :habit_id,
          references(:habits,
            column: :id,
            name: "plan_entries_habit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create constraint(:plan_entries, :plan_entries_exactly_one_target,
             check: """
               (todo_id IS NOT NULL)::int + (habit_id IS NOT NULL)::int = 1
             """
           )
  end

  def down do
    drop_if_exists constraint(:plan_entries, :plan_entries_exactly_one_target)

    drop constraint(:plan_entries, "plan_entries_user_id_fkey")

    drop constraint(:plan_entries, "plan_entries_todo_id_fkey")

    drop constraint(:plan_entries, "plan_entries_habit_id_fkey")

    drop table(:plan_entries)
  end
end
