defmodule Electricbrain.Repo.Migrations.AddMetricGoals do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:metrics) do
      add :period, :text
      add :goal_kind, :text
      add :goal_value, :decimal
    end
  end

  def down do
    alter table(:metrics) do
      remove :goal_value
      remove :goal_kind
      remove :period
    end
  end
end
