defmodule Electricbrain.Repo.Migrations.AddTimeBlocks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:time_blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :duration_minutes, :bigint
      add :buffer_before_minutes, :bigint, null: false, default: 0
      add :buffer_after_minutes, :bigint, null: false, default: 0
      add :weekly_target_minutes, :bigint
      add :target_kind, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "time_blocks_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :category_id,
          references(:categories,
            column: :id,
            name: "time_blocks_category_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create table(:time_block_availabilities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :day_of_week, :bigint
      add :start_time, :time, null: false
      add :end_time, :time, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "time_block_availabilities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :time_block_id,
          references(:time_blocks,
            column: :id,
            name: "time_block_availabilities_time_block_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    alter table(:plan_entries) do
      add :time_block_id,
          references(:time_blocks,
            column: :id,
            name: "plan_entries_time_block_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    drop_if_exists constraint(:plan_entries, :plan_entries_exactly_one_target)

    create constraint(:plan_entries, :plan_entries_exactly_one_target,
             check: """
               (todo_id IS NOT NULL)::int + (habit_id IS NOT NULL)::int + (time_block_id IS NOT NULL)::int = 1
             """
           )
  end

  def down do
    drop_if_exists constraint(:plan_entries, :plan_entries_exactly_one_target)

    create constraint(:plan_entries, :plan_entries_exactly_one_target,
             check: """
               (todo_id IS NOT NULL)::int + (habit_id IS NOT NULL)::int = 1
             """
           )

    drop constraint(:plan_entries, "plan_entries_time_block_id_fkey")

    alter table(:plan_entries) do
      remove :time_block_id
    end

    drop constraint(:time_block_availabilities, "time_block_availabilities_user_id_fkey")

    drop constraint(:time_block_availabilities, "time_block_availabilities_time_block_id_fkey")

    drop table(:time_block_availabilities)

    drop constraint(:time_blocks, "time_blocks_user_id_fkey")

    drop constraint(:time_blocks, "time_blocks_category_id_fkey")

    drop table(:time_blocks)
  end
end
