defmodule Electricbrain.Repo.Migrations.AddFocusSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :focus_work_minutes, :bigint, null: false, default: 25
      add :focus_break_minutes, :bigint, null: false, default: 5
    end

    create table(:focus_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "running"
      add :duration_minutes, :bigint, null: false, default: 25
      add :break_minutes, :bigint, null: false, default: 5
      add :started_at, :utc_datetime_usec, null: false
      add :break_started_at, :utc_datetime_usec
      add :ended_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "focus_sessions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :todo_id,
          references(:todos,
            column: :id,
            name: "focus_sessions_todo_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :habit_id,
          references(:habits,
            column: :id,
            name: "focus_sessions_habit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :time_block_id,
          references(:time_blocks,
            column: :id,
            name: "focus_sessions_time_block_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :category_id,
          references(:categories,
            column: :id,
            name: "focus_sessions_category_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create constraint(:focus_sessions, :focus_sessions_at_most_one_target,
             check: """
               (todo_id IS NOT NULL)::int + (habit_id IS NOT NULL)::int + (time_block_id IS NOT NULL)::int + (category_id IS NOT NULL)::int <= 1
             """
           )
  end

  def down do
    drop_if_exists constraint(:focus_sessions, :focus_sessions_at_most_one_target)

    drop constraint(:focus_sessions, "focus_sessions_user_id_fkey")

    drop constraint(:focus_sessions, "focus_sessions_todo_id_fkey")

    drop constraint(:focus_sessions, "focus_sessions_habit_id_fkey")

    drop constraint(:focus_sessions, "focus_sessions_time_block_id_fkey")

    drop constraint(:focus_sessions, "focus_sessions_category_id_fkey")

    drop table(:focus_sessions)

    alter table(:users) do
      remove :focus_break_minutes
      remove :focus_work_minutes
    end
  end
end
