defmodule Electricbrain.Repo.Migrations.AddShoppingListItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:shopping_list_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :total_quantity_g, :decimal, null: false
      add :checked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :meal_week_id,
          references(:meal_weeks,
            column: :id,
            name: "shopping_list_items_meal_week_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :ingredient_id,
          references(:ingredients,
            column: :id,
            name: "shopping_list_items_ingredient_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "shopping_list_items_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:shopping_list_items, [:meal_week_id, :ingredient_id],
             name: "shopping_list_items_one_per_ingredient_index"
           )
  end

  def down do
    drop constraint(:shopping_list_items, "shopping_list_items_meal_week_id_fkey")

    drop constraint(:shopping_list_items, "shopping_list_items_ingredient_id_fkey")

    drop constraint(:shopping_list_items, "shopping_list_items_user_id_fkey")

    drop_if_exists unique_index(:shopping_list_items, [:meal_week_id, :ingredient_id],
                     name: "shopping_list_items_one_per_ingredient_index"
                   )

    drop table(:shopping_list_items)
  end
end
