defmodule Electricbrain.Repo.Migrations.AddMealsIngredients do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ingredients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :source, :text, null: false, default: "custom"
      add :afcd_code, :text
      add :kcal_per_100g, :decimal, null: false
      add :protein_g_per_100g, :decimal, null: false
      add :fat_g_per_100g, :decimal, null: false
      add :carbs_g_per_100g, :decimal, null: false
      add :fibre_g_per_100g, :decimal, null: false, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "ingredients_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:ingredients, [:afcd_code], name: "ingredients_afcd_code_index")
  end

  def down do
    drop constraint(:ingredients, "ingredients_user_id_fkey")

    drop_if_exists unique_index(:ingredients, [:afcd_code], name: "ingredients_afcd_code_index")

    drop table(:ingredients)
  end
end
