defmodule Electricbrain.Repo.Migrations.RitualSteps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:habit_step_checks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :checked_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "habit_step_checks_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :completion_id,
          references(:habit_completions,
            column: :id,
            name: "habit_step_checks_completion_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :ritual_step_id, :uuid, null: false
    end

    create unique_index(:habit_step_checks, [:completion_id, :ritual_step_id],
             name: "habit_step_checks_unique_check_index"
           )

    create table(:habit_ritual_steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:habit_step_checks) do
      modify :ritual_step_id,
             references(:habit_ritual_steps,
               column: :id,
               name: "habit_step_checks_ritual_step_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:habit_ritual_steps) do
      add :title, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "habit_ritual_steps_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :habit_id,
          references(:habits,
            column: :id,
            name: "habit_ritual_steps_habit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    alter table(:habit_completions) do
      modify :completed_at, :utc_datetime_usec, null: true
    end
  end

  def down do
    alter table(:habit_completions) do
      modify :completed_at, :utc_datetime_usec, null: false
    end

    drop constraint(:habit_ritual_steps, "habit_ritual_steps_user_id_fkey")

    drop constraint(:habit_ritual_steps, "habit_ritual_steps_habit_id_fkey")

    alter table(:habit_ritual_steps) do
      remove :habit_id
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :title
    end

    drop constraint(:habit_step_checks, "habit_step_checks_ritual_step_id_fkey")

    alter table(:habit_step_checks) do
      modify :ritual_step_id, :uuid
    end

    drop table(:habit_ritual_steps)

    drop constraint(:habit_step_checks, "habit_step_checks_user_id_fkey")

    drop constraint(:habit_step_checks, "habit_step_checks_completion_id_fkey")

    drop_if_exists unique_index(:habit_step_checks, [:completion_id, :ritual_step_id],
                     name: "habit_step_checks_unique_check_index"
                   )

    drop table(:habit_step_checks)
  end
end
