defmodule Electricbrain.Repo.Migrations.HabitCountFieldsOptional do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:habits) do
      modify :period, :text, null: true, default: nil
      modify :min_count, :bigint, null: true, default: nil
    end
  end

  def down do
    alter table(:habits) do
      modify :min_count, :bigint, null: false, default: 1
      modify :period, :text, null: false, default: "week"
    end
  end
end
