defmodule Electricbrain.Repo.Migrations.AddGoogleEventIdToEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:plan_entries) do
      add :google_event_id, :text
    end
  end

  def down do
    alter table(:plan_entries) do
      remove :google_event_id
    end
  end
end
