defmodule Electricbrain.Repo.Migrations.AllowNilDayOfWeek do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:habit_availabilities) do
      modify :day_of_week, :bigint, null: true
    end
  end

  def down do
    alter table(:habit_availabilities) do
      modify :day_of_week, :bigint, null: false
    end
  end
end
