defmodule Electricbrain.Repo.Migrations.AddTrainingCore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:training_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "training_templates_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:training_templates, [:user_id, :name],
             name: "training_templates_unique_name_per_user_index"
           )

    create table(:training_template_slots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false, default: 0
      add :kind, :text, null: false, default: "fixed"
      add :sets, :bigint, null: false, default: 3
      add :reps, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :template_id,
          references(:training_templates,
            column: :id,
            name: "training_template_slots_template_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :exercise_id, :uuid
      add :user_id, :uuid, null: false
    end

    create table(:training_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :training_days, {:array, :bigint}, null: false
      add :reminder_time, :time, null: false, default: fragment("'06:30:00'")
      add :default_rest_seconds, :bigint, null: false, default: 180
      add :last_reminded_on, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "training_settings_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:training_settings, [:user_id],
             name: "training_settings_one_per_user_index"
           )

    create table(:training_exercise_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :current_weight_kg, :decimal
      add :current_reps, :bigint
      add :consecutive_stalls, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :exercise_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create unique_index(:training_exercise_states, [:user_id, :exercise_id],
             name: "training_exercise_states_one_per_exercise_index"
           )

    create table(:training_exercises, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:training_template_slots) do
      modify :exercise_id,
             references(:training_exercises,
               column: :id,
               name: "training_template_slots_exercise_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "training_template_slots_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:training_exercise_states) do
      modify :exercise_id,
             references(:training_exercises,
               column: :id,
               name: "training_exercise_states_exercise_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "training_exercise_states_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:training_exercises) do
      add :name, :text, null: false
      add :kind, :text, null: false
      add :progression, :text, null: false
      add :increment_kg, :decimal
      add :start_reps, :bigint
      add :rep_ceiling, :bigint
      add :deload_pct, :decimal, null: false, default: "10"
      add :stall_threshold, :bigint, null: false, default: 3
      add :rest_seconds, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "training_exercises_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :top_set_metric_id,
          references(:metrics,
            column: :id,
            name: "training_exercises_top_set_metric_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :e1rm_metric_id,
          references(:metrics,
            column: :id,
            name: "training_exercises_e1rm_metric_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:training_exercises, [:user_id, :name],
             name: "training_exercises_unique_name_per_user_index"
           )
  end

  def down do
    drop constraint(:training_exercises, "training_exercises_user_id_fkey")

    drop constraint(:training_exercises, "training_exercises_top_set_metric_id_fkey")

    drop constraint(:training_exercises, "training_exercises_e1rm_metric_id_fkey")

    drop_if_exists unique_index(:training_exercises, [:user_id, :name],
                     name: "training_exercises_unique_name_per_user_index"
                   )

    alter table(:training_exercises) do
      remove :e1rm_metric_id
      remove :top_set_metric_id
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :rest_seconds
      remove :stall_threshold
      remove :deload_pct
      remove :rep_ceiling
      remove :start_reps
      remove :increment_kg
      remove :progression
      remove :kind
      remove :name
    end

    drop constraint(:training_exercise_states, "training_exercise_states_exercise_id_fkey")

    drop constraint(:training_exercise_states, "training_exercise_states_user_id_fkey")

    alter table(:training_exercise_states) do
      modify :user_id, :uuid
      modify :exercise_id, :uuid
    end

    drop constraint(:training_template_slots, "training_template_slots_exercise_id_fkey")

    drop constraint(:training_template_slots, "training_template_slots_user_id_fkey")

    alter table(:training_template_slots) do
      modify :user_id, :uuid
      modify :exercise_id, :uuid
    end

    drop table(:training_exercises)

    drop_if_exists unique_index(:training_exercise_states, [:user_id, :exercise_id],
                     name: "training_exercise_states_one_per_exercise_index"
                   )

    drop table(:training_exercise_states)

    drop constraint(:training_settings, "training_settings_user_id_fkey")

    drop_if_exists unique_index(:training_settings, [:user_id],
                     name: "training_settings_one_per_user_index"
                   )

    drop table(:training_settings)

    drop constraint(:training_template_slots, "training_template_slots_template_id_fkey")

    drop table(:training_template_slots)

    drop constraint(:training_templates, "training_templates_user_id_fkey")

    drop_if_exists unique_index(:training_templates, [:user_id, :name],
                     name: "training_templates_unique_name_per_user_index"
                   )

    drop table(:training_templates)
  end
end
