defmodule Electricbrain.Repo.Migrations.AddCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "categories_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :parent_id,
          references(:categories,
            column: :id,
            name: "categories_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end
  end

  def down do
    drop constraint(:categories, "categories_user_id_fkey")

    drop constraint(:categories, "categories_parent_id_fkey")

    drop table(:categories)
  end
end
