defmodule Electricbrain.Repo.Migrations.AddTodoRecurrence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:todos) do
      add :recurrence, :text, null: false, default: "none"
      add :recurrence_anchor, :utc_datetime_usec
    end
  end

  def down do
    alter table(:todos) do
      remove :recurrence_anchor
      remove :recurrence
    end
  end
end
