defmodule Electricbrain.Repo.Migrations.AddHabitReflection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:habit_reflections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :week_start, :date, null: false
      add :notes, :text
      add :difficulty, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "habit_reflections_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :habit_id,
          references(:habits,
            column: :id,
            name: "habit_reflections_habit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:habit_reflections, [:habit_id, :week_start],
             name: "habit_reflections_unique_habit_week_index"
           )
  end

  def down do
    drop constraint(:habit_reflections, "habit_reflections_user_id_fkey")

    drop constraint(:habit_reflections, "habit_reflections_habit_id_fkey")

    drop_if_exists unique_index(:habit_reflections, [:habit_id, :week_start],
                     name: "habit_reflections_unique_habit_week_index"
                   )

    drop table(:habit_reflections)
  end
end
