defmodule Electricbrain.Repo.Migrations.EntryDurationOverride do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:plan_entries) do
      add :duration_minutes, :bigint
    end
  end

  def down do
    alter table(:plan_entries) do
      remove :duration_minutes
    end
  end
end
