defmodule Electricbrain.Repo.Migrations.DropNoteBodyDrawing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notes) do
      remove :drawing
      remove :body
    end
  end

  def down do
    alter table(:notes) do
      add :body, :text, default: ""
      add :drawing, :map
    end
  end
end
