defmodule Electricbrain.Repo.Migrations.AddNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:push_subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :endpoint, :text, null: false
      add :p256dh_key, :text, null: false
      add :auth_key, :text, null: false
      add :user_agent, :text
      add :last_used_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "push_subscriptions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:push_subscriptions, [:user_id, :endpoint],
             name: "push_subscriptions_unique_endpoint_per_user_index"
           )

    alter table(:plan_entries) do
      add :notified_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:plan_entries) do
      remove :notified_at
    end

    drop constraint(:push_subscriptions, "push_subscriptions_user_id_fkey")

    drop_if_exists unique_index(:push_subscriptions, [:user_id, :endpoint],
                     name: "push_subscriptions_unique_endpoint_per_user_index"
                   )

    drop table(:push_subscriptions)
  end
end
