defmodule Electricbrain.Repo.Migrations.AddCategoryColor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:categories) do
      add :color_id, :bigint
    end
  end

  def down do
    alter table(:categories) do
      remove :color_id
    end
  end
end
