defmodule Electricbrain.Repo.Migrations.AddG2DevicePairing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:device_pairings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token_hash, :text, null: false
      add :label, :text, null: false
      add :last_seen_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "device_pairings_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:device_pairings, [:token_hash],
             name: "device_pairings_unique_token_hash_index"
           )

    create table(:device_pairing_codes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text, null: false
      add :expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "device_pairing_codes_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:device_pairing_codes, [:code],
             name: "device_pairing_codes_unique_code_index"
           )
  end

  def down do
    drop constraint(:device_pairing_codes, "device_pairing_codes_user_id_fkey")

    drop_if_exists unique_index(:device_pairing_codes, [:code],
                     name: "device_pairing_codes_unique_code_index"
                   )

    drop table(:device_pairing_codes)

    drop constraint(:device_pairings, "device_pairings_user_id_fkey")

    drop_if_exists unique_index(:device_pairings, [:token_hash],
                     name: "device_pairings_unique_token_hash_index"
                   )

    drop table(:device_pairings)
  end
end
