defmodule Electricbrain.Repo.Migrations.AddMoments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:moments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :name, :text, null: false
      add :intensity, :bigint, null: false, default: 3
      add :recognize, :text
      add :allow, :text
      add :investigate, :text
      add :nurture, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "moments_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :category_id,
          references(:categories,
            column: :id,
            name: "moments_category_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end
  end

  def down do
    drop constraint(:moments, "moments_user_id_fkey")

    drop constraint(:moments, "moments_category_id_fkey")

    drop table(:moments)
  end
end
