defmodule Electricbrain.Repo.Migrations.AddSchedulable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:todos) do
      add :duration_minutes, :bigint
      add :buffer_before_minutes, :bigint, null: false, default: 0
      add :buffer_after_minutes, :bigint, null: false, default: 0
    end

    create table(:todo_availabilities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :day_of_week, :bigint, null: false
      add :start_time, :time, null: false
      add :end_time, :time, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "todo_availabilities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :todo_id,
          references(:todos,
            column: :id,
            name: "todo_availabilities_todo_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    alter table(:habits) do
      add :duration_minutes, :bigint
      add :buffer_before_minutes, :bigint, null: false, default: 0
      add :buffer_after_minutes, :bigint, null: false, default: 0
    end

    create table(:habit_availabilities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :day_of_week, :bigint, null: false
      add :start_time, :time, null: false
      add :end_time, :time, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "habit_availabilities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :habit_id,
          references(:habits,
            column: :id,
            name: "habit_availabilities_habit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:habit_availabilities, "habit_availabilities_user_id_fkey")

    drop constraint(:habit_availabilities, "habit_availabilities_habit_id_fkey")

    drop table(:habit_availabilities)

    alter table(:habits) do
      remove :buffer_after_minutes
      remove :buffer_before_minutes
      remove :duration_minutes
    end

    drop constraint(:todo_availabilities, "todo_availabilities_user_id_fkey")

    drop constraint(:todo_availabilities, "todo_availabilities_todo_id_fkey")

    drop table(:todo_availabilities)

    alter table(:todos) do
      remove :buffer_after_minutes
      remove :buffer_before_minutes
      remove :duration_minutes
    end
  end
end
