defmodule Electricbrain.Repo.Migrations.AddCategoryToTodoAndInboxKind do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:todos) do
      add :category_id,
          references(:categories,
            column: :id,
            name: "todos_category_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    alter table(:categories) do
      add :kind, :text, null: false, default: "standard"
    end
  end

  def down do
    alter table(:categories) do
      remove :kind
    end

    drop constraint(:todos, "todos_category_id_fkey")

    alter table(:todos) do
      remove :category_id
    end
  end
end
