defmodule Electricbrain.Repo.Migrations.AddEntryCompletionState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:plan_entries) do
      add :completed_at, :utc_datetime_usec
      add :dismissed_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:plan_entries) do
      remove :dismissed_at
      remove :completed_at
    end
  end
end
