defmodule Electricbrain.Repo.Migrations.AddHabits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:habits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :min_count, :bigint, null: false, default: 1
      add :period, :text, null: false, default: "week"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "habits_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :category_id,
          references(:categories,
            column: :id,
            name: "habits_category_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create table(:habit_completions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :completed_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "habit_completions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :habit_id,
          references(:habits,
            column: :id,
            name: "habit_completions_habit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:habit_completions, "habit_completions_user_id_fkey")

    drop constraint(:habit_completions, "habit_completions_habit_id_fkey")

    drop table(:habit_completions)

    drop constraint(:habits, "habits_user_id_fkey")

    drop constraint(:habits, "habits_category_id_fkey")

    drop table(:habits)
  end
end
