defmodule Electricbrain.Repo.Migrations.AddTrainingWorkouts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:training_workouts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "active"
      add :template_name, :text
      add :started_at, :utc_datetime_usec, null: false
      add :ended_at, :utc_datetime_usec
      add :metrics_logged_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "training_workouts_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :template_id,
          references(:training_templates,
            column: :id,
            name: "training_workouts_template_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:training_workout_sets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :exercise_name, :text, null: false
      add :position, :bigint, null: false
      add :set_number, :bigint, null: false
      add :slot_kind, :text, null: false, default: "fixed"
      add :target_reps, :bigint, null: false
      add :prescribed_weight_kg, :decimal
      add :actual_reps, :bigint
      add :completed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workout_id,
          references(:training_workouts,
            column: :id,
            name: "training_workout_sets_workout_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :exercise_id,
          references(:training_exercises,
            column: :id,
            name: "training_workout_sets_exercise_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "training_workout_sets_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:training_workout_sets, "training_workout_sets_workout_id_fkey")

    drop constraint(:training_workout_sets, "training_workout_sets_exercise_id_fkey")

    drop constraint(:training_workout_sets, "training_workout_sets_user_id_fkey")

    drop table(:training_workout_sets)

    drop constraint(:training_workouts, "training_workouts_user_id_fkey")

    drop constraint(:training_workouts, "training_workouts_template_id_fkey")

    drop table(:training_workouts)
  end
end
