defmodule Electricbrain.Repo.Migrations.AddMealsRecipes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:recipes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slot_type, :text, null: false
      add :servings, :decimal, null: false, default: "1"
      add :instructions, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "recipes_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:recipe_ingredients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity_g, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :recipe_id,
          references(:recipes,
            column: :id,
            name: "recipe_ingredients_recipe_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :ingredient_id,
          references(:ingredients,
            column: :id,
            name: "recipe_ingredients_ingredient_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "recipe_ingredients_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:recipe_ingredients, [:recipe_id, :ingredient_id],
             name: "recipe_ingredients_unique_per_recipe_index"
           )
  end

  def down do
    drop constraint(:recipe_ingredients, "recipe_ingredients_recipe_id_fkey")

    drop constraint(:recipe_ingredients, "recipe_ingredients_ingredient_id_fkey")

    drop constraint(:recipe_ingredients, "recipe_ingredients_user_id_fkey")

    drop_if_exists unique_index(:recipe_ingredients, [:recipe_id, :ingredient_id],
                     name: "recipe_ingredients_unique_per_recipe_index"
                   )

    drop table(:recipe_ingredients)

    drop constraint(:recipes, "recipes_user_id_fkey")

    drop table(:recipes)
  end
end
