defmodule Electricbrain.Repo.Migrations.AddOuraTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :oura_access_token, :text
      add :oura_refresh_token, :text
      add :oura_token_expires_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:users) do
      remove :oura_token_expires_at
      remove :oura_refresh_token
      remove :oura_access_token
    end
  end
end
