defmodule Electricbrain.Repo.Migrations.DropHabitFixedSchedule do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:habits) do
      remove :fixed_schedule
      modify :min_count, :bigint, null: false
    end
  end

  def down do
    alter table(:habits) do
      modify :min_count, :bigint, null: true
      add :fixed_schedule, :boolean, null: false, default: false
    end
  end
end
