defmodule Electricbrain.Repo.Migrations.AddProfileMetrics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:profile_metrics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :nutrition_profile_id,
          references(:nutrition_profiles,
            column: :id,
            name: "profile_metrics_nutrition_profile_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :metric_id,
          references(:metrics,
            column: :id,
            name: "profile_metrics_metric_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "profile_metrics_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:profile_metrics, [:nutrition_profile_id, :metric_id],
             name: "profile_metrics_unique_per_profile_index"
           )
  end

  def down do
    drop constraint(:profile_metrics, "profile_metrics_nutrition_profile_id_fkey")

    drop constraint(:profile_metrics, "profile_metrics_metric_id_fkey")

    drop constraint(:profile_metrics, "profile_metrics_user_id_fkey")

    drop_if_exists unique_index(:profile_metrics, [:nutrition_profile_id, :metric_id],
                     name: "profile_metrics_unique_per_profile_index"
                   )

    drop table(:profile_metrics)
  end
end
