defmodule Electricbrain.Repo.Migrations.AddMetrics do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:metrics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :unit, :text, null: false
      add :aggregation, :text, null: false, default: "point"
      add :group_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "metrics_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :category_id,
          references(:categories,
            column: :id,
            name: "metrics_category_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create table(:measurements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :value, :decimal, null: false
      add :recorded_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "measurements_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :metric_id,
          references(:metrics,
            column: :id,
            name: "measurements_metric_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :completion_id,
          references(:habit_completions,
            column: :id,
            name: "measurements_completion_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create table(:habit_metrics, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "habit_metrics_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :habit_id,
          references(:habits,
            column: :id,
            name: "habit_metrics_habit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :metric_id,
          references(:metrics,
            column: :id,
            name: "habit_metrics_metric_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:habit_metrics, [:habit_id, :metric_id],
             name: "habit_metrics_unique_habit_metric_index"
           )
  end

  def down do
    drop constraint(:habit_metrics, "habit_metrics_user_id_fkey")

    drop constraint(:habit_metrics, "habit_metrics_habit_id_fkey")

    drop constraint(:habit_metrics, "habit_metrics_metric_id_fkey")

    drop_if_exists unique_index(:habit_metrics, [:habit_id, :metric_id],
                     name: "habit_metrics_unique_habit_metric_index"
                   )

    drop table(:habit_metrics)

    drop constraint(:measurements, "measurements_user_id_fkey")

    drop constraint(:measurements, "measurements_metric_id_fkey")

    drop constraint(:measurements, "measurements_completion_id_fkey")

    drop table(:measurements)

    drop constraint(:metrics, "metrics_user_id_fkey")

    drop constraint(:metrics, "metrics_category_id_fkey")

    drop table(:metrics)
  end
end
