defmodule Electricbrain.Repo.Migrations.AddMealWeeks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:planned_meals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :date, :date, null: false
      add :slot, :text, null: false
      add :servings, :decimal, null: false
      add :notified_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :meal_week_id, :uuid, null: false
      add :recipe_id, :uuid, null: false
      add :user_id, :uuid, null: false
    end

    create unique_index(:planned_meals, [:meal_week_id, :date, :slot],
             name: "planned_meals_one_per_slot_index"
           )

    create table(:meal_weeks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:planned_meals) do
      modify :meal_week_id,
             references(:meal_weeks,
               column: :id,
               name: "planned_meals_meal_week_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :recipe_id,
             references(:recipes,
               column: :id,
               name: "planned_meals_recipe_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "planned_meals_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:meal_weeks) do
      add :week_start, :date, null: false
      add :status, :text, null: false, default: "draft"
      add :target_kcal, :bigint, null: false
      add :target_protein_g, :bigint, null: false
      add :target_fat_g, :bigint, null: false
      add :target_carbs_g, :bigint, null: false
      add :warnings, {:array, :text}, null: false, default: []
      add :shopping_notified_at, :utc_datetime_usec
      add :prep_notified_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "meal_weeks_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:meal_weeks, [:user_id, :week_start],
             name: "meal_weeks_one_per_week_index"
           )
  end

  def down do
    drop constraint(:meal_weeks, "meal_weeks_user_id_fkey")

    drop_if_exists unique_index(:meal_weeks, [:user_id, :week_start],
                     name: "meal_weeks_one_per_week_index"
                   )

    alter table(:meal_weeks) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :prep_notified_at
      remove :shopping_notified_at
      remove :warnings
      remove :target_carbs_g
      remove :target_fat_g
      remove :target_protein_g
      remove :target_kcal
      remove :status
      remove :week_start
    end

    drop constraint(:planned_meals, "planned_meals_meal_week_id_fkey")

    drop constraint(:planned_meals, "planned_meals_recipe_id_fkey")

    drop constraint(:planned_meals, "planned_meals_user_id_fkey")

    alter table(:planned_meals) do
      modify :user_id, :uuid
      modify :recipe_id, :uuid
      modify :meal_week_id, :uuid
    end

    drop table(:meal_weeks)

    drop_if_exists unique_index(:planned_meals, [:meal_week_id, :date, :slot],
                     name: "planned_meals_one_per_slot_index"
                   )

    drop table(:planned_meals)
  end
end
