defmodule Electricbrain.Repo.Migrations.AddNoteBlocks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:note_blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, null: false, default: 0
      add :kind, :text, null: false
      add :data, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "note_blocks_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :note_id,
          references(:notes,
            column: :id,
            name: "note_blocks_note_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:note_blocks, "note_blocks_user_id_fkey")

    drop constraint(:note_blocks, "note_blocks_note_id_fkey")

    drop table(:note_blocks)
  end
end
