defmodule Electricbrain.Repo.Migrations.AddHabitIdentityAndMinimumAction do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:habits) do
      add :identity_statement, :text
      add :minimum_viable_action, :text
    end
  end

  def down do
    alter table(:habits) do
      remove :minimum_viable_action
      remove :identity_statement
    end
  end
end
