defmodule Electricbrain.Repo.Migrations.AddNutritionProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:nutrition_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :height_cm, :decimal
      add :birthdate, :date
      add :sex, :text
      add :activity_level, :text, null: false, default: "light"
      add :goal, :text, null: false, default: "maintain"
      add :goal_rate_kcal_per_day, :bigint, null: false, default: 400
      add :protein_g_per_kg, :decimal, null: false, default: "2.0"
      add :fat_pct, :decimal, null: false, default: "25"
      add :override_kcal, :bigint
      add :override_protein_g, :bigint
      add :override_fat_g, :bigint
      add :override_carbs_g, :bigint
      add :breakfast_time, :time, null: false, default: fragment("'07:00:00'")
      add :shake_time, :time, null: false, default: fragment("'10:00:00'")
      add :lunch_time, :time, null: false, default: fragment("'12:30:00'")
      add :snack_time, :time, null: false, default: fragment("'15:00:00'")
      add :dinner_time, :time, null: false, default: fragment("'18:30:00'")
      add :shopping_reminder_time, :time, null: false, default: fragment("'08:00:00'")
      add :prep_reminder_time, :time, null: false, default: fragment("'09:00:00'")
      add :max_shakes_per_day, :bigint, null: false, default: 2
      add :last_nudged_on, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "nutrition_profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :weight_metric_id,
          references(:metrics,
            column: :id,
            name: "nutrition_profiles_weight_metric_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create unique_index(:nutrition_profiles, [:user_id],
             name: "nutrition_profiles_one_per_user_index"
           )
  end

  def down do
    drop constraint(:nutrition_profiles, "nutrition_profiles_user_id_fkey")

    drop constraint(:nutrition_profiles, "nutrition_profiles_weight_metric_id_fkey")

    drop_if_exists unique_index(:nutrition_profiles, [:user_id],
                     name: "nutrition_profiles_one_per_user_index"
                   )

    drop table(:nutrition_profiles)
  end
end
